# Generated by Django 5.1.4 on 2025-01-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper_stat', '0002_alter_base_options_alter_call_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='parameters',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
